// Load environment variables from server/.env
// Example: PORT, MONGODB_URI, NODE_ENV, JWT_SECRET, etc.
import "./config/env.js";

// Import Node.js function used to create the HTTP server.
// We use createServer(app) instead of app.listen()
// because Socket.IO also needs access to the HTTP server.
import { createServer } from "node:http";

// Gets information about the computer's network adapters,
// such as Wi-Fi, Ethernet, and their IP addresses.
import { networkInterfaces } from "node:os";

// Import the configured Express application.
// app.js contains Express middleware, routes, etc.
import app from "./app.js";

// Import the function responsible for connecting to MongoDB.
import connectDB from "./config/database.js";

// Import the function that attaches Socket.IO
// to our Node.js HTTP server.
import { attachSocketServer } from "./realtime/socketServer.js";

// Functions related to ultrasonic telemetry.
//
// hydrateLatestReading():
// Restores the latest saved sensor readings from MongoDB
// into backend memory when the server starts.
//
// getLatestReading:
// Returns the latest reading currently known by the backend.
import {
  hydrateLatestReading,
  getLatestReading,
} from "./services/ultrasonicReadingService.js";

// Restores the latest saved device control state,
// such as AUTO/MANUAL mode, system enabled,
// manual pump state, etc.
import { hydrateDeviceControlState } from "./services/deviceControlService.js";

// Alert-related functions.
//
// hydrateOpenAlerts():
// Restores active/unresolved alerts after backend restart.
//
// sweepOfflineDevices():
// Checks whether devices stopped sending telemetry.
import {
  hydrateOpenAlerts,
  sweepOfflineDevices,
} from "./services/alertService.js";

// Synchronizes device access information when backend starts.
// This is related to Owner, Controller, and Viewer access.
import { syncDeviceMembersOnBoot } from "./services/deviceAccessService.js";


// ---------------------------------------------------------
// SERVER CONFIGURATION
// ---------------------------------------------------------

// Read PORT from .env.
// If PORT does not exist, use 5000 as the default.
//
// Example:
// process.env.PORT = 6000 → use 6000
// no PORT defined         → use 5000
const PORT = process.env.PORT || 5000;

// 0.0.0.0 means the backend listens on every network interface.
//
// This is important because the ESP32 is another device
// on the same Wi-Fi/LAN network.
//
// 127.0.0.1 would allow only localhost.
// 0.0.0.0 allows localhost + LAN devices.
const HOST = "0.0.0.0";


// ---------------------------------------------------------
// CREATE HTTP SERVER
// ---------------------------------------------------------

// Create a Node.js HTTP server using our Express app.
//
// Express handles the REST API requests,
// while the HTTP server itself can also be used by Socket.IO.
const server = createServer(app);

// Attach Socket.IO to the same HTTP server.
//
// So the same server can handle:
//
// HTTP REST API
// +
// Socket.IO real-time communication
attachSocketServer(server);


// ---------------------------------------------------------
// HTTP SERVER ERROR HANDLING
// ---------------------------------------------------------

// Listen for errors generated by the HTTP server.
server.on("error", (error) => {

  // EADDRINUSE means the selected port is already
  // being used by another process.
  //
  // Example:
  // Another Node.js server may already be using port 5000.
  if (error.code === "EADDRINUSE") {

    console.error(
      `[Startup] Port ${PORT} is already in use. ` +
      `Run "netstat -ano | findstr :${PORT}", identify the listening PID, ` +
      `then stop only that process with "taskkill /PID <PID> /F".`
    );

    // Stop the Node.js process because the server
    // cannot start correctly.
    //
    // exit code 1 = program stopped because of an error.
    process.exit(1);
  }

  // Handle any other HTTP server error.
  console.error("[Startup] HTTP server failed:", error);

  // Stop the application because startup failed.
  process.exit(1);
});


// ---------------------------------------------------------
// OFFLINE DEVICE CHECK CONFIGURATION
// ---------------------------------------------------------

// The backend checks every 5 seconds whether
// an ESP32 device stopped reporting telemetry.
//
// JavaScript allows underscores inside numbers for readability:
//
// 5_000 = 5000 milliseconds = 5 seconds
const OFFLINE_SWEEP_INTERVAL_MS = 5_000;


// ---------------------------------------------------------
// DATABASE CONNECTION + STARTUP PROCESS
// ---------------------------------------------------------

// First connect to MongoDB.
//
// connectDB() returns a Promise,
// so we use:
//
// .then()
// .then()
// .catch()
//
// to control the startup sequence.
connectDB()

  // -------------------------------------------------------
  // AFTER DATABASE CONNECTION
  // -------------------------------------------------------

  // When MongoDB connects successfully,
  // restore important saved application state.
  .then(() =>
    Promise.all([

      // Restore latest ESP32/tank telemetry readings.
      hydrateLatestReading(),

      // Restore pump/device control settings.
      hydrateDeviceControlState(),

      // Restore alerts that are still active.
      hydrateOpenAlerts(),

      // Synchronize device Owner/Controller/Viewer records.
      syncDeviceMembersOnBoot(),
    ])
  )


  // -------------------------------------------------------
  // START OFFLINE DEVICE MONITORING
  // -------------------------------------------------------

  // This runs after all hydration/synchronization
  // operations above finish successfully.
  .then(() => {

    // setInterval() repeatedly executes a function.
    //
    // Here it runs every 5 seconds.
    const offlineSweep = setInterval(() => {

      // Check devices to determine whether
      // any stopped sending telemetry.
      //
      // Notice:
      //
      // getLatestReading
      //
      // has NO parentheses.
      //
      // We are passing the function itself,
      // not calling it immediately.
      sweepOfflineDevices(getLatestReading)

        // If one offline check fails,
        // print the error but DO NOT stop the entire backend.
        .catch((error) => {
          console.error(
            "[Alerts] Offline sweep failed:",
            error.message
          );
        });

    }, OFFLINE_SWEEP_INTERVAL_MS);


    // unref() tells Node.js:
    //
    // "Do not keep the entire application alive
    // only because this timer exists."
    //
    // ?. is optional chaining.
    //
    // It means:
    // call unref() only if it exists.
    offlineSweep.unref?.();
  })


  // -------------------------------------------------------
  // START THE HTTP SERVER
  // -------------------------------------------------------

  .then(() => {

    // Start accepting HTTP connections.
    //
    // PORT:
    // normally 5000
    //
    // HOST:
    // 0.0.0.0 → accept LAN/network connections
    server.listen(PORT, HOST, () => {

      // Print the server environment and address.
      //
      // process.env.NODE_ENV || "development"
      //
      // means:
      // use NODE_ENV if it exists,
      // otherwise use "development".
      console.log(
        `Server running in ${
          process.env.NODE_ENV || "development"
        } mode at http://${HOST}:${PORT}`
      );


      // Show a reminder of the endpoint
      // that the ESP32 should use for telemetry.
      //
      // Example:
      //
      // http://172.17.160.47:5000/api/sensors/ultrasonic
      console.log(
        `[Startup] Point the ESP32 at ` +
        `http://<laptop-lan-ip>:${PORT}/api/sensors/ultrasonic`
      );


      // ---------------------------------------------------
      // FIND AND PRINT LAPTOP NETWORK IP ADDRESSES
      // ---------------------------------------------------

      // networkInterfaces() returns network adapters
      // such as:
      //
      // Wi-Fi
      // Ethernet
      // VMware adapters
      //
      // Object.entries() converts the object
      // into [key, value] pairs.
      //
      // Example:
      //
      // ["Wi-Fi", addresses]
      //
      // Then:
      //
      // name      = "Wi-Fi"
      // addresses = array of IP information
      for (
        const [name, addresses]
        of Object.entries(networkInterfaces())
      ) {

        // Loop through every address belonging
        // to this network interface.
        //
        // ?? [] means:
        //
        // if addresses is null or undefined,
        // use an empty array instead.
        for (const address of addresses ?? []) {

          // We only want:
          //
          // 1. IPv4 addresses
          // 2. Non-internal addresses
          //
          // address.internal = true
          // usually means localhost such as 127.0.0.1.
          //
          // !address.internal means:
          // NOT internal.
          if (
            address.family === "IPv4" &&
            !address.internal
          ) {

            // Print the adapter name and LAN address.
            //
            // Example:
            //
            // Wi-Fi: http://172.17.160.47:5000
            //
            // This helps us know which IP
            // the ESP32 should connect to.
            console.log(
              `[Startup]   ${name}: ` +
              `http://${address.address}:${PORT}`
            );
          }
        }
      }
    });
  })


  // -------------------------------------------------------
  // HANDLE STARTUP FAILURE
  // -------------------------------------------------------

  // If something in the main Promise chain fails,
  // such as:
  //
  // - MongoDB connection
  // - telemetry hydration
  // - control-state hydration
  // - alert hydration
  // - device-member synchronization
  //
  // execution reaches this catch().
  .catch((error) => {

    console.error(
      "Failed to connect to database:",
      error
    );

    // Stop the application because initialization failed.
    process.exit(1);
  });